services:
  traefik:
    image: traefik:latest
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--api.dashboard=true"
      - "--api.insecure=true" # ⚠ accès libre, à retirer en prod
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.dashboard.address=:9001"

    environment:
      - DOCKER_API_VERSION=1.40
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "glance.name=Traefik"
      - "glance.icon=si:traefikproxy"
      - "glance.url=http(`traefik.local`)"
      - "glance.description=Reverse Proxy"
      - "glance.id=traefik"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - bme_network
      - bme_network_aux
  # Portainer UI
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`${SUBDOMAIN}-portainer.${DOMAIN}`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "glance.name=Portainer"
      - "glance.icon=si:portainer"
      - "glance.url=http://${SUBDOMAIN}-portainer.${DOMAIN}"
      - "glance.description=Container Management"
      - "glance.id=portainer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mnt/portainer/data:/data
    networks:
      - bme_network
      - bme_network_aux
  adminer:
    image: adminer:latest
    container_name: adminer
    networks:
      - bme_network
      - bme_network_aux
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`${SUBDOMAIN}-adminer.${DOMAIN}`)"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
  oracle:
    image: gvenzl/oracle-xe:21-slim
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD:-password}
      APP_USER: ${ORACLE_USER:-RGZ}
      APP_USER_PASSWORD: ${ORACLE_USER_PASSWORD:-password}
      NLS_LANG: FRENCH_FRANCE.AL32UTF8
    ports:
      - "1521:1521"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.oracle.rule=Host(`${SUBDOMAIN}-oracle.${DOMAIN}`)"
      - "traefik.http.services.oracle.loadbalancer.server.port=1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - bme_network
      - bme_network_aux
  mailer:
    container_name: mailer
    image: axllent/mailpit:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailer.rule=Host(`${SUBDOMAIN}-mailer.${DOMAIN}`)"
      - "traefik.http.services.mailer.loadbalancer.server.port=8025"
      - "glance.name=Mailpit"
      - "glance.icon=si:mailtrap"
      - "glance.url=http://${SUBDOMAIN}-mailer.${DOMAIN}"
      - "glance.description=Mail Catcher & Testing"
      - "glance.id=mailpit"
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # HTTP (UI)
    networks:
      bme_network:
        aliases:
            - ${SUBDOMAIN}-mailer.${DOMAIN}
      bme_network_aux:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    environment:
      - DOCKER_API_VERSION=1.40
    volumes:
      - ./mnt/glance/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - bme_network
      - bme_network_aux
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.glance.rule=Host(`${SUBDOMAIN}-glance.${DOMAIN}`)"
      - "traefik.http.services.glance.loadbalancer.server.port=8080"
  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ./mnt/organizr/config:/config
    restart: unless-stopped
    depends_on:
      - traefik
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.organizr.rule=Host(`${SUBDOMAIN}-organizr.${DOMAIN}`)"
      - "traefik.http.services.organizr.loadbalancer.server.port=80"
    networks:
      - bme_network
      - bme_network_aux
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
      MARIADB_DATABASE: ${MARIADB_DATABASE:-db_master}
      MARIADB_USER: ${MARIADB_USER:-admin}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-password}
    volumes:
      - ./mnt/mariadb/data:/var/lib/mysql
      - ./mnt/adminer/config:/etc/mysql/conf.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mariadb.rule=Host(`${SUBDOMAIN}-mariadb.${DOMAIN}`)"
      - "traefik.http.services.mariadb.loadbalancer.server.port=3306"
      - "glance.name=MariaDB"
      - "glance.icon=si:mariadb"
      - "glance.url=http://${SUBDOMAIN}-mariadb.${DOMAIN}"
      - "glance.description=SQL Database (MariaDB)"
      - "glance.id=mariadb"
    networks:
      - bme_network
      - bme_network_aux
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`${SUBDOMAIN}-dozzle.${DOMAIN}`)"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      - "glance.name=Dozzle"
      - "glance.icon=si:docker"
      - "glance.url=http://${SUBDOMAIN}-dozzle.${DOMAIN}"
      - "glance.description=Real-time Log Viewer"
      - "glance.id=dozzle"
    networks:
      - bme_network
      - bme_network_aux
    restart: unless-stopped
volumes:
  portainer_data:
  organizer_data:
  oracle_data:
  mariadb_data:

networks:
  bme_network:
    external: true
  bme_network_aux:
    external: true
