#!/bin/bash

# Configuration
HOSTS_FILE="/mnt/c/Windows/System32/drivers/etc/hosts"
IP_ADDRESS="127.0.0.1"
COMMENT="# generated by traefik sync"

# Vérifier si Docker est installé
if ! command -v docker &> /dev/null; then
    echo "Erreur : 'docker' n'est pas installé ou n'est pas dans le PATH."
    exit 1
fi

echo "Récupération des hôtes depuis les labels Docker..."

CONTAINERS=$(docker ps -aq)
if [ -z "$CONTAINERS" ]; then
    echo "Aucun conteneur Docker trouvé."
    exit 0
fi

HOSTS=$(docker inspect $CONTAINERS --format '{{range $k, $v := .Config.Labels}}{{println $v}}{{end}}' 2>/dev/null | \
    grep "Host(" | \
    sed -E 's/.*Host\(`([^`]*)`\).*/\1/' | \
    tr ',' '\n' | \
    sed -E 's/`//g' | \
    tr -d " " | \
    sort -u)

if [ -z "$HOSTS" ]; then
    echo "Aucun hôte Traefik trouvé dans les labels Docker."
    exit 0
fi

echo "Hôtes trouvés :"
echo "$HOSTS"
echo "--------------------------------"

if [ ! -f "$HOSTS_FILE" ]; then
    echo "Erreur : Le fichier $HOSTS_FILE est introuvable."
    exit 1
fi

# 1. Lire le fichier hosts et supprimer TOUTES les lignes gérées par traefik (anciennes, nouvelles, corrompues)
# On utilise grep -v pour exclure les lignes contenant le commentaire (ou la version corrompue t#)
CLEAN_CONTENT=$(grep -vE "(# generated by traefik sync|t# generated by traefik sync)" "$HOSTS_FILE")

# 2. Préparer les nouvelles lignes
NEW_ENTRIES=""
for HOST in $HOSTS; do
    NEW_ENTRIES+="$IP_ADDRESS    $HOST    $COMMENT\n"
done

# 3. Réassembler le contenu
# On s'assure qu'il y a une nouvelle ligne à la fin du contenu original s'il n'est pas vide
if [ -n "$CLEAN_CONTENT" ]; then
    FINAL_CONTENT="$CLEAN_CONTENT\n\n$NEW_ENTRIES"
else
    FINAL_CONTENT="$NEW_ENTRIES"
fi

# 4. Écrire le fichier
echo "Mise à jour du fichier hosts..."
if echo -e "$FINAL_CONTENT" | sudo tee "$HOSTS_FILE" > /dev/null; then
    echo "[OK] Fichier hosts mis à jour avec succès."
else
    echo "L'écriture directe a échoué. Tentative via PowerShell (élévation requise)..."
    WIN_HOSTS_FILE="C:\\Windows\\System32\\drivers\\etc\\hosts"
    # On utilise un fichier temporaire côté Windows pour simplifier l'appel
    TEMP_FILE="C:\\Windows\\Temp\\hosts_traefik_temp"
    echo -e "$FINAL_CONTENT" > /tmp/hosts_new
    cp /tmp/hosts_new /mnt/c/Windows/Temp/hosts_traefik_temp 2>/dev/null
    
    powershell.exe -Command "Start-Process powershell -ArgumentList '-Command \"Move-Item -Force $TEMP_FILE $WIN_HOSTS_FILE\"' -Verb RunAs" -Wait
    if [ $? -eq 0 ]; then
        echo "[OK] Mise à jour via PowerShell réussie."
    else
        echo "[ERREUR] Échec de la mise à jour."
        exit 1
    fi
fi

echo "--------------------------------"
echo "Terminé."
