# Configuration
$HostsFile = "$env:SystemRoot\System32\drivers\etc\hosts"
$IpAddress = "127.0.0.1"
$Comment = "# generated by traefik sync"

$DockerCmd = "docker"

Write-Host "Vérification de Docker..." -ForegroundColor Cyan
if (!(Get-Command $DockerCmd -ErrorAction SilentlyContinue)) {
    if (Get-Command wsl -ErrorAction SilentlyContinue) {
        $WslTest = wsl bash -l -c "command -v docker" 2>$null
        if ($WslTest) {
            Write-Host "Docker trouvé dans WSL. Utilisation de 'wsl docker'." -ForegroundColor Yellow
            $DockerCmd = "wsl", "docker"
        } else {
            Write-Error "Erreur : 'docker' n'est pas installé sur Windows ni dans WSL."
            exit 1
        }
    } else {
        Write-Error "Erreur : 'docker' n'est pas installé ou n'est pas dans le PATH."
        exit 1
    }
}

function Invoke-Docker {
    param([string[]]$Arguments)
    if ($DockerCmd -is [array]) {
        $FullArgs = $Arguments -join " "
        wsl bash -l -c "docker $FullArgs"
    } else {
        & $DockerCmd $Arguments
    }
}

Write-Host "Récupération des hôtes depuis les labels Docker..." -ForegroundColor Cyan
$Containers = Invoke-Docker -Arguments @("ps", "-aq")
if (-not $Containers) {
    Write-Host "Aucun conteneur Docker trouvé."
    exit 0
}

$ContainerIds = $Containers -join " "
$RawJson = Invoke-Docker -Arguments @("inspect", $ContainerIds, "--format", "'{{json .Config.Labels}}'")
$Hosts = @()

foreach ($Line in $RawJson) {
    if ($Line -eq "null" -or -not $Line) { continue }
    try {
        $Labels = $Line | ConvertFrom-Json
        foreach ($Key in $Labels.PSObject.Properties.Name) {
            $Value = $Labels.$Key
            if ($Value -match 'Host\(`([^`]+)`\)') {
                $Matches = [regex]::Matches($Value, 'Host\(`([^`]+)`\)')
                foreach ($Match in $Matches) {
                    $HostValue = $Match.Groups[1].Value
                    $Hosts += $HostValue -split '`,`'
                }
            }
        }
    } catch {}
}

$Hosts = $Hosts | ForEach-Object { $_.Trim('`').Trim() } | Select-Object -Unique | Where-Object { $_ -ne "" }

if (-not $Hosts) {
    Write-Host "Aucun hôte Traefik trouvé dans les labels Docker."
    exit 0
}

Write-Host "Hôtes trouvés :" -ForegroundColor Green
$Hosts | ForEach-Object { Write-Host " - $_" }
Write-Host "--------------------------------"

# 1. Lire le fichier actuel et filtrer les lignes traefik (anciennes ou corrompues)
$CurrentContent = Get-Content $HostsFile
$CleanContent = $CurrentContent | Where-Object { 
    $_ -notmatch [regex]::Escape($Comment) -and $_ -notmatch "t# generated by traefik sync" 
}

# 2. Préparer les nouvelles lignes
$NewEntries = $Hosts | ForEach-Object { "$IpAddress    $_    $Comment" }

# 3. Réassembler le contenu
$FinalContent = $CleanContent
if ($CleanContent -and $NewEntries) {
    $FinalContent += "" # Ligne vide de séparation
}
$FinalContent += $NewEntries

# 4. Écrire le fichier
$IsAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

if ($IsAdmin) {
    $FinalContent | Set-Content $HostsFile
    Write-Host "[OK] Fichier hosts mis à jour avec succès." -ForegroundColor Green
} else {
    Write-Host "Élévation des privilèges nécessaire pour modifier le fichier hosts..." -ForegroundColor Cyan
    $TempFile = [System.IO.Path]::GetTempFileName()
    $FinalContent | Set-Content $TempFile
    
    $Command = "Move-Item -Force '$TempFile' '$HostsFile'"
    try {
        Start-Process powershell -ArgumentList "-NoProfile -ExecutionPolicy Bypass -Command $Command" -Verb RunAs -Wait
        Write-Host "[OK] Mise à jour réussie (via fenêtre d'autorisation Windows)." -ForegroundColor Green
    } catch {
        Write-Error "Échec de la mise à jour : Vous devez accepter la demande d'autorisation Administrateur."
    }
}
